### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by n0um3n4**

### CODE REVIEW

**Comment by mayra-cabrera** [comment]
we should also delete "logo.png" file.. we don't need anymore 💃

**Review by mayra-cabrera — COMMENTED** [review]
Besides the comment I made about deleting the old logo, this LGTM!

**Review by mayra-cabrera — APPROVED** [review]

**Comment by mayra-cabrera** [comment]
@thelastinuit Since you didn't answer me, I had to do the arrangements myself 💅

**Comment by n0um3n4** [comment]
Sorry, do as you need or want. 
This is your unwanted baby, now. Make it way more better, way more.

**Pull request merged**
